### ISSUE TITLE
Predictions based on staypoints and regularly visited POIs

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#101]
As a final feature for the first version, the app is supposed to predict when the user is about to leave for a regularly visited POI (see https://github.com/sitcomlab/simport-learning-app/issues/100). One way of doing this in a simple way could be setting up something like a schedule / timetable for the whole week that contains (for every hour or half our?) the most visited location (or an approximation if it) or POI. This lookup table is updated constantly and from time to time it is checked for regularities or patterns (e.g. daily or weekly cycles). If a pattern is detected, we can use it for a simple prediction that is then presented to the user.

This concept is still very rough around the edges and before implemented something like this it would make sense to invest a bit of time in background research.

**Comment by felixerdy** [comment]
In order to store regularly visited POIs in the DB, we need to persist inferences. Currently, the generation of new inferences causes the deletion of all existing inferences before storing the new inferences in the database.

Therefore we need to update already existing inferences that are already stored in the db

**Comment by felixerdy** [comment]
<img height="564" alt="Bildschirmfoto 2021-11-23 um 16 59 43" src="https://user-images.githubusercontent.com/12086004/143059096-3a1e0de1-a582-4105-b361-2a4c89c2b795.png">

Just for discussion: an example of a heatmap that can be visualised in the "Explore" tab based on the timetable data

**Comment by felixerdy** [comment]
As the [background fetch plugin](https://github.com/transistorsoft/cordova-plugin-background-fetch) just allows one instance, all configured background fetch functions will run at the same time. Differentiating the tasks based on the `taskId` ([like described here](https://github.com/transistorsoft/cordova-plugin-background-fetch#%EF%B8%8F-ios)) did not work for me as all tasks were running under the same `taskId` on android.
