### ISSUE TITLE
ESM / diary modus

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#123]
For the first study, users will be asked to look at their data and reflect on it. In addition, we want to offer them the opportunity to report their reflection (if desired) into the app.

- [x] outline UI/UX concept
- [x] implement text field entry
- [x] store entries in database
- [x] export entries

**Comment by felixerdy** [comment]
Initial diary concept now in branch `feature/diary`

| Adds a new entry to main page | Lists all entries in diary with some content. Additionally, an export button allows to export your diary |
| ------------- | ------------- |
| ![](https://user-images.githubusercontent.com/12086004/146038445-9e10f88b-a539-4696-8826-97c70d6cb079.png)  | ![](https://user-images.githubusercontent.com/12086004/146039118-31e56d54-63d8-40f7-96e3-38bae2c319fa.png)  |

| Detail view of an entry | Create new entry / edit entry view |
| ------------- | ------------- |
| ![](https://user-images.githubusercontent.com/12086004/146039364-86569964-ace1-46e7-8fe2-b3e05646f1bf.png)  | ![](https://user-images.githubusercontent.com/12086004/146039569-410b4813-1085-4c7a-a790-66aaf92e48cf.png) |

Open for discussion 🙂

**Comment by felixerdy** [comment]
UI concepts of map page:

| Header | in FAB list | new FAB |
| ------------- | ------------- | ------------- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2021-12-15 at 10 25 17](https://user-images.githubusercontent.com/12086004/146166950-1c8c00a4-36af-4c2b-abac-aa3233884a54.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2021-12-15 at 11 11 56](https://user-images.githubusercontent.com/12086004/146167491-d047d81f-2174-4049-9844-2cacef26d863.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2021-12-15 at 11 01 29](https://user-images.githubusercontent.com/12086004/146166865-a52e100a-f078-4550-83d7-a1529ad851d6.png) |

Opening modal on button click
<img src="https://user-images.githubusercontent.com/12086004/146167840-1cf5ff6c-c987-4391-b950-b333c5e97c24.png" width=300 />

**Comment by felixerdy** [comment]
Shall we allow writing the content in markdown so that users can format their content? 

Pros: allows users to format their content

Cons: could lead to unwanted formatting if users are unaware of markdown syntax as there may be a need to escape special characters

**Comment by zven** [comment]
@felixerdy Although I am personally a huge fan of markdown, I honestly think that it would confuse most users if we include text formatting via markdown.

**Comment by zven** [comment]
Update after meeting:

- UI diary feature: Putting the diary feature into a prominent, easily reachable place in the map view would definitely make sense. This way, the user does not need to click through several sub menus.
- Export: To make things more easy for the users, exporting the whole diary as a file (e.g. txt or csv) should also trigger an email intent where the recipient and subject are pre-filled with the diary file as an attachment (to be sent to us). Fallback solution if user doesn't have an email account on their phone / does not want to send it via mail: Export to file system.
