### ISSUE TITLE
Trajectory visualization: Avoid straight connections between gaps

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#125]
At the moment, we simply connect all the points of a trajectory with a straight line, regardless if there was a gap in the recording or not. This can result in rather odd looking trajectory with straight  lines over long distances that look as if the user was flying from A to B.

Since we have the information when the tracking is started stored in the database, we can avoid the issue mentioned above.

Some guiding questions:

- The `start` information is stored in the database. Does the model that is displayed on the map already contain this information?

**Comment by JuanFFranco** [comment]
Managed to delete the straight lines when there's a `start` . 

![Screenshot_2021-12-17-19-10-47-192_de ifgi simport learning2](https://user-images.githubusercontent.com/76211446/147046509-445fc1ce-5dee-4555-811f-674575d8270d.jpg) ![Screenshot_2021-12-17-19-13-39-584_de ifgi simport learning2](https://user-images.githubusercontent.com/76211446/147046534-29e1b615-f2d3-4fb1-88a1-3cdae320782e.jpg)

**Comment by JuanFFranco** [comment]
Identified straight lines when there's no `start` point, for example when loses gps signal or flight mode.

![Screenshot_2021-12-22-07-54-59-941_de ifgi simport learning2](https://user-images.githubusercontent.com/76211446/147049255-6e468ff7-6dd3-43ef-be66-e38fb27c8f3c.jpg)

**Comment by JuanFFranco** [comment]
###  `mapBounds` issue found.

`mapBounds` are fixed, but identified the issue when the user travels large distances. The map will show the whole trajectory, making it difficult to identify where the inferences are located within a small area.

`mapBounds` could be redefined depending on the last records only and not on the whole trajectory.

![Screenshot_2021-12-28-10-51-47-112_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/147553998-2b4fba72-37c0-4857-9a1d-f90d2408b0f5.jpg)

###  Identifying signal loss.

Straight lines are only deleted when there's a `start` identified. This keeps showing straight lines when there is GPS signal loss, for example when the user uses flight mode or when going through tunnels. 

![Screenshot_2021-12-28-11-03-28-739_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/147554882-4f79ce84-0c71-4715-889c-5c6e00f4181d.jpg)

#### Literature proposes methodologies of signal loss identification depending on the logging technique used.

* Continuous Logging: 
Uses a predefined threshold for the time difference between two consecutive points. Also possible having thresholds for speed, acceleration, heading and distance.

* Movement Only Logging:
Only compares the distance of two consecutive points when the trajectory is being recorded only when the device is moving.

* Distance Logging:
Compares also the distance between two consecutive points when the trajectory is being recorded depending on the distance. If this distance difference is greater than the defined for the recording, then there is a possible signal loss in that section.

**Comment by zven** [comment]
@schrooom, @felixerdy and @jbraese What do you think? All of the solutions that @JuanFFranco has highlighted make assumptions that might not work for us. Distance logging _could_ work but I am almost inclined to stick to the simple way of removing the straight lines between explicit stops and starts.

**Comment by schrooom** [comment]
> @schrooom, @felixerdy and @jbraese What do you think? All of the solutions that @JuanFFranco has highlighted make assumptions that might not work for us. Distance logging _could_ work but I am almost inclined to stick to the simple way of removing the straight lines between explicit stops and starts.

I agree with you. We could consider distance logging using a fairly high threshold, which would at least roughly cleanup the trajectory by filtering out "extreme straights" with a negligible risk of false positives. That threshold could e.g. be set to 10km – a distance were we can be fairly sure, that such a straight line does not have any real value to our system.

**Comment by jbraese** [comment]
> > @schrooom, @felixerdy and @jbraese What do you think? All of the solutions that @JuanFFranco has highlighted make assumptions that might not work for us. Distance logging _could_ work but I am almost inclined to stick to the simple way of removing the straight lines between explicit stops and starts.
> 
> I agree with you. We could consider distance logging using a fairly high threshold, which would at least roughly cleanup the trajectory by filtering out "extreme straights" with a negligible risk of false positives. That threshold could e.g. be set to 10km – a distance were we can be fairly sure, that such a straight line does not have any real value to our system.

Agreed as well. I think some large cut-off based on distance can work. I am not sure which value I'd choose though; if the cut-off is too small, we would have many disjointed trajectories which I think would be quite disorienting, potentially more so than some large straight lines during a train journey.

**Comment by JuanFFranco** [comment]
I already tried applying a threshold for this, and found out that 6 km is the maximum for deleting the straight lines from the last screenshot, when certainly I was going through tunnels and on the subway, but faced the trouble that when I was on a highway, there still some gaps on the trajectory in the second screenshot.


![Screenshot_1641917563](https://user-images.githubusercontent.com/76211446/148980094-ab1f0a42-4588-4ee6-96ba-d9d71779b42b.png) ![Screenshot_1641917588](https://user-images.githubusercontent.com/76211446/148980404-22b27211-a79e-49b7-a9cf-9d018c2616d3.png)

But this approach also worked for the example trajectory in Nepal.

![Screenshot_1641918120](https://user-images.githubusercontent.com/76211446/148981179-647ec00e-2e0f-4618-8e0c-d9a1c8099467.png)
