### ISSUE TITLE
Prepare settings and imprint page

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#130]
The app is still lacking an imprint page (which we should have for our first study) and a place where we could list the used open source libraries and licenses. Those could be sub-pages of a settings page.
Please implement a settings page that can be opened from the upper right corner of the start screen (e.g. by clicking on a cog-icon). The user should be able to navigate back to the front page with an arrow icon that is located in the top left corner (please see existing pages in the app). On this page should be two options / buttons that open separate pages:
- an "Imprint" button that opens the imprint page
- an "Open source licenses" button that opens the license page
For now, it is sufficient if both pages contain Lorem ipsum text that we replace with meaningful text later (not part of this card). You could, for example, use https://loremipsum.io/generator/ to create some placeholder text.

To implement this feature, you'd need to familiarize yourself first with the basics of Angular (like creation and use of models, components, pages and navigation). Here, I'd suggest to try out the Angular "Tour of heroes" tutorial (https://angular.io/tutorial) and the Ionic/Angular tutorial (https://ionicframework.com/docs/angular/your-first-app). This will teach you some basic concepts that will help you for implement the settings and imprint page.

Todos:
- [x] Angular "Tour of heroes" tutorial (https://angular.io/tutorial)
- [x] Ionic/Angular tutorial (https://ionicframework.com/docs/angular/your-first-app)
- [x] add settings button to front page of app with cog icon
- [x] "Settings" page is opened on button press
- [x] "Settings" page allows to navigate back to previous page
- [x] button that opens "Imprint" page (filled with lorem ipsum text)
- [x] button that opens "Open source licenses" page (filled with lorm ipsum text)

Hints:
- When implementing the tutorials, it could make sense to track them in an own github repository where you commit you changes bit by bit.
- When working on the actual feature, please create an extra branch (e.g. "feature/settings-page") and commit your changes step by step with meaningful commit messages (e.g. `#130: add settings button to main page`).
- In case sth. is unclear, you are stuck or you feel that you need some feedback, please get in touch with one of us. :-)
- You can edit this comment to adjust the proposed todos in the list.

**Comment by JuanFFranco** [comment]
- Added settings button to start page.

![Screenshot_1642579623](https://user-images.githubusercontent.com/76211446/150089609-695d22de-af88-4dfc-a0c9-5b5cf6629878.png)

**Comment by JuanFFranco** [comment]
- Created settings page with back button.

![Screenshot_1643041501](https://user-images.githubusercontent.com/76211446/150822905-4a53c3ba-6324-48d3-9f9e-4cb43d01af76.png)

**Comment by JuanFFranco** [comment]
- Added buttons to settings page and functions.

![Screenshot_1643042821](https://user-images.githubusercontent.com/76211446/150826903-29faba6e-fb96-42d0-8f5e-1070dfa6452c.png)

- Created the imprint and open source licenses page wit back button.

![Screenshot_1643042882](https://user-images.githubusercontent.com/76211446/150827212-8652c30e-2839-427f-8b55-5d2874b56106.png) ![Screenshot_1643042930](https://user-images.githubusercontent.com/76211446/150827156-c9c1c0a1-9252-4a78-ae07-d3f2ee9b26a6.png)

**Comment by JuanFFranco** [comment]
- Added Lorem ipsum text to both pages.

![Screenshot_1643044266](https://user-images.githubusercontent.com/76211446/150831024-1df4f323-a8aa-4cb2-acb2-30cd88616c70.png) ![Screenshot_1643044270](https://user-images.githubusercontent.com/76211446/150831034-2bf817b8-9bc7-4157-8bed-be379687cd29.png)

**Comment by zven** [comment]
@JuanFFranco In case your feature is ready for review, please also create a pull request and link it to this issue. This way, the review process is easier for the reviewer.
