### ISSUE TITLE
Beta lane release on Android

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#134]
- [x] Who (organization / account) releases the app? -> Institute for Geoinformatics of WWU
- [ ] test release in beta lane

**Comment by felixerdy** [comment]
Maybe a litte bit overkill but we might take a look at https://fastlane.tools/ which promises to make builds and releases more simple

**Comment by felixerdy** [comment]
**Internal test vs closed test**
According to [googles documentation], one can invite up to 100 persons to an internal test while the closed test can be used for a larger group of people. Despite this difference, it seems like google will not give feedback to internal test apps but only on closed test apps [stackoverflow]. 

I'd suggest to start with the internal test and just do it similar to the workflow of the [stackoverflow] answer:

> 1. I set the app as Internal testing (even if it is just my email address) . Right after doing this I
> 2. Promote the app to "Close testing" (even if it is just my email address) - so I can get Google's report right away.
> 3. After getting Google's report and fixing what they suggest (or ignoring it), I promote the app to production.


[googles documentation]: https://support.google.com/googleplay/android-developer/answer/9845334
[stackoverflow]: https://stackoverflow.com/a/72031644

**Comment by zven** [comment]
Seems like a legit way of approaching things: For our internal tests, it would not make much of a difference if we have an internal or closed test. The additional benefit of following the outlined procedure would be that we get google's report quite fast so we get to know potential issues and have the chance to fix those.

**Comment by felixerdy** [comment]
I got access to a google play service account which we can use to upload new releases to the play store from a github action. I added a secret file to our repository and added the github action in the [feature/android-beta](https://github.com/sitcomlab/simport-learning-app/compare/feature/android-beta) branch. This will trigger a new internal beta release in the play store when someone pushes to a (yet not existing) `study-1` branch
