### ISSUE TITLE
Add licenses for third party libs

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#137]
To my knowledge, it's good practice to acknowledge the used open source libraries somewhere in you app. We should also do that.

**Comment by felixerdy** [comment]
Initial implementation:

<img src="https://user-images.githubusercontent.com/12086004/152961272-220a7bcc-17a3-44f1-88bb-5624731b0c27.png" width=300/>


Generates a licenses.json file in the assets folder in the `postinstall` script, so this file should always be up to date.

**Comment by felixerdy** [comment]
Do we need to include `devDependencies`?
