### ISSUE TITLE
Informed consent info text under start / stop tracking button

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#145]

**Comment by JuanFFranco** [comment]
The app should be compliance by following some GDPR regulations, avoiding the users to overlook when they should agree to the privacy policies. From that and following some examples in other apps, we have these options:

![Screenshot_1645197523](https://user-images.githubusercontent.com/76211446/154710591-1aac7725-bbb6-469a-94dc-a594a5c46a23.png) ![Screenshot_1645197176](https://user-images.githubusercontent.com/76211446/154710586-5617f47d-b39b-4bb5-9743-7f303c432b61.png)  ![Screenshot_1645197065](https://user-images.githubusercontent.com/76211446/154710583-b3046396-4e78-446f-add5-4371e488dbf3.png) ![Screenshot_1645197294](https://user-images.githubusercontent.com/76211446/154710589-df1266ec-5fe8-46ea-aa8a-a730016d5511.png)

**Comment by JuanFFranco** [comment]
Checkbox and alert function. Missing configuring alert to show up only the first time that opens the app.

![Screenshot_1646206291](https://user-images.githubusercontent.com/76211446/156315391-b5fa4224-d74c-44db-a213-02723934ecc7.png)

**Comment by JuanFFranco** [comment]
Pull request #180
