### ISSUE TITLE
Test and build execution: use npm ci

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#169]
@jbraese realized, while working on https://github.com/sitcomlab/simport-learning-app/issues/158, that we are using `npm install` for our automated build, test and deployment processes. To execute those with a clean install, it's advised to use`npm ci` instead: https://docs.npmjs.com/cli/v8/commands/npm-ci

**Comment by felixerdy** [comment]
I think we should first investigate https://github.com/sitcomlab/simport-learning-app/pull/166#issuecomment-1066698159 in #166 as `npm config set package-lock false` installs different versions of packages (which you can see in the /src/assets/licenses.json file generated in the postinstall script). Other than that `npm ci` works fine for me and also triggers the postinstall script which is nice.
