### ISSUE TITLE
Replace Nepal example trajectory with something that makes more sense (and can be analyzed)

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#170]
At the moment, we have a rather large Nepal trajectory that can not be analyzed for inferences. Although the analysis is not important for the study, something that makes a bit more sense and is smaller might be beneficial (e.g. for explaining the basic functionality). Maybe we can re-use one the artificial test datasets that are used for the automated tests?

Mentioned here: https://github.com/sitcomlab/simport-learning-app/issues/156

**Comment by zven** [comment]
@JuanFFranco the script `dev\generate_test_trajectory.ts` creates a set of test trajectories based on the content of the `test-data-gpx` folder and stores them in a format that is then used in the automatic test execution (see `package.json`) and could be used to replace the nepal trajectory. If you are struggling with executing the script, please ping me. :-)

**Comment by JuanFFranco** [comment]
When executing the script, and try all trajectories generated, is not possible to generate inferences. 

![Screenshot_20220506_184816](https://user-images.githubusercontent.com/76211446/167177039-e4b281c5-58a4-45ee-96f3-137fca46cb01.png) ![Screenshot_20220506_184835](https://user-images.githubusercontent.com/76211446/167177086-3d4e05d0-dd8e-4a2a-94a9-0d687dd97d7f.png)

**Comment by JuanFFranco** [comment]
I created a new Trajectory, that when I import it, creates inferences with no problem, but when I replace the Nepal trajectory to this one, the app won't create inferences from it. I'm not sure if there's an extra step when importing the json file that does not occur when reading the example json file. 
- When replacing `example` trajectory:

![Screenshot_20220527_190141](https://user-images.githubusercontent.com/76211446/170748179-7a6c9616-2914-4209-9a5f-41ea982daa14.png)
- When `importing` trajectory:

![Screenshot_20220527_190157](https://user-images.githubusercontent.com/76211446/170748238-478dee61-c162-4470-8377-c49e6a7a335a.png)

**Comment by zven** [comment]
Idea for fix:

- try to import example trajectory on app start into database
- check on every start if it is already there

**Comment by JuanFFranco** [comment]
Only missing fixing the sorting of the trajectories in the Select Trajectory Page

**Comment by JuanFFranco** [comment]
Just realized a small flaw,  if the trajectory is threated as a TrajectoryType.EXAMPLE is not possible to delete the trajectory, but as this new trajectory is still TrajectoryType.IMPORT, only with a badge that says example, it will be possible to delete it, but if the user does it, won't be possible to get it back.

![Screenshot_2022-06-27-23-11-04-835_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/176036563-eef15b3d-83bf-45fe-8267-b749fd832a12.jpg)
