### ISSUE TITLE
Functionality diary button: Access old entries?

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#171]
As @thierna has noted while testing the app (https://github.com/sitcomlab/simport-learning-app/issues/156): When the user clicks on the diary button, a menu for adding a new entry pops up.
However, the user might expect to have access to their previous diary entries as well. As an alternative, the diary button on the map would open the diary menu.

Before implementing this, we should discuss the implications etc.

**Comment by felixerdy** [comment]
We coud add an additional button which would open the diary page. I'm not sure about the placement though 

| Header | Block Button | Floating Action Button |
|---|---|---|
| <img width="516" alt="Bildschirmfoto 2022-03-21 um 10 08 36" src="https://user-images.githubusercontent.com/12086004/159231807-4ad082f3-fbbc-41ca-ae40-34aeb8a80710.png"> | <img width="516" alt="Bildschirmfoto 2022-03-21 um 10 12 27" src="https://user-images.githubusercontent.com/12086004/159232373-5340ff48-3ef9-4189-8a95-0bb466c8dec0.png"> | <img width="516" alt="Bildschirmfoto 2022-03-21 um 10 15 24" src="https://user-images.githubusercontent.com/12086004/159232829-9406a1c7-34af-43f1-bd00-55379386cf71.png"> |

**Comment by zven** [comment]
I would tend to the the "Block Button"-option.
I think the list icon in the header next to the X is a bit too small and the floating action button seems to be a bit out of place. But that's just my opinion. What do you think @thierna?

**Comment by thierna** [comment]
I would have thought to open the diary menu but this would mean an additional click to create a new entry. I like the button that says "meine Einträge öffnen" but I would place it at the bottom of the page so that it doesnt distract from creating a new entry. also would make it less blue.
