### ISSUE TITLE
Import of example trajectory causes app to crash

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#173]
As found out in https://github.com/sitcomlab/simport-learning-app/issues/156, re-importing the example trajectory causes the app to crash.

Since this is a rather unusual case, I'd say we fix it if it's something small.

![](https://user-images.githubusercontent.com/7602648/155109413-9065caef-a32a-4c8a-a85e-1cd80c031511.png)

**Comment by JuanFFranco** [comment]
I wasn't able to reproduce this error when using the #170 new example trajectory. Don't know if this could be related to the trajectory itself.

When I try to reproduce the same from the develop branch, I don't get the same error, just that after a couple of minutes importing, I simply can't see the Nepal trajectory on the map.

![Screenshot_2022-05-27-19-19-47-923_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/170760017-eaf92eb4-a12b-4858-b287-78e182d44ee8.jpg)
