### ISSUE TITLE
Map view does not center on collected trajectory data but on Münster

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#174]
As @jbraese mentioned on https://github.com/sitcomlab/simport-learning-app/issues/156: "If I click on the map it opens in some region in Münster, and not where my saved trajectory points are, these aren't visible until I scroll to where I live manually."

There seems to be something wrong with the initial bounding box. My first guess would be that some hardcoded coordinates for when the map loads point to the Münster area.

**Comment by felixerdy** [comment]
#175 sets the map bounds to null island. The map should however always set the bounds to your trajectory after loading.
