### ISSUE TITLE
Update wording of logbook questions

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#178]
We should formulate those questions as neutral as possible to not prime our participants on the privacy topic.

German:
"Haben Sie sich heute Ihre Ortsdaten angeschaut? Falls ja: Welche Beobachtungen haben Sie gemacht?"

English:
"Have you looked at your location data today? If yes: What observations have you made?"

**Comment by JuanFFranco** [comment]
Was not sure where to place the phrases, so don't know if it should be here.

![Screenshot_1650429205](https://user-images.githubusercontent.com/76211446/164151058-b81ce4d9-ef97-4f4b-937a-d6218e1206d1.png)

**Comment by zven** [comment]
@JuanFFranco I think you forgot to create a pull request. ;-)

**Comment by felixerdy** [comment]
Closed in #190
