### ISSUE TITLE
Stop / pause tracking feature

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#184]
Motivation:
- pausing / stopping tracking -> use as indicator for privacy preserving behaviour
- ensure that the user can turn off tracking in case they do not feel comfortable with being tracked during the study

Potential ways of realizing this (ordered from very drastic to less drastic):
- user turns off phone
- user turns location services off
- user kills app
- user stops tracking in app menu
- user pauses tracking in app menu

Basic premise?
- users are not allowed to turn off location services on phones during study

Possible workflows:
1. location tracking runs (running state is persisted) -> user kills app -> after some (potentially very long) time -> user restarts app -> app checks if location tracking was still active before startup -> location tracking is started again by app
2. location tracking is running -> user stops tracking in app menu -> user would need to start it manually by opening the app again and navigating to the tracking menu
3. location tracking runs -> user hits pause button -> tracking stops for X hours (how do we define X?) -> tracking restarts automatically (is that even possible? how could that be realized? do we need an extra background service that could be killed as well? via remote notifications?)
4. more refined version: location tracking runs -> user hits pause button -> user can enter length X of pause period -> tracking stops for X hours -> tracking restarts automatically (idea: app fires scheduled notification with attached code that restarts tracking after X hours. Alternative: make use of a background service or task?)

As a first shot, I'd suggest to try out workflow 4.

**Comment by jbraese** [comment]
As there was no reliable way of turning the tracking back on automatically in Capactitor 2, the pausing is currently implemented as turning the background tracking off, displaying the state of tracking as paused in the UI, and scheduling a notification asking the user to take action and turn the tracking back on when the pause time has ended. Screenshots of the current UI are below.

I have two open questions at the moment:

1. How long do we give the option to pause? Currently, a choice is given between: 30min, 60min, 90min, 2h, 3h, 4h.

2. What do we display in the UI when the tracking is paused?
	- Currently it displays the button to turn tracking back on, with the state subtitle indicating that tracking has been paused.
	- We could add something like "Paused until ..." by persisting the unpause date somewhere (right now it is only used to schedule a notification but not safed). My concern is that if we display "paused until ..." we might give the impression that the tracking turns on automatically, which we cannot currently do. 

Any feedback on this or the general UI is appreciated.


![1](https://user-images.githubusercontent.com/47788955/166211659-80325409-e6c0-4538-918b-e22769264dca.png)
![2](https://user-images.githubusercontent.com/47788955/166211663-d9b2ae57-f05c-41cc-a0b1-27de205aab14.png)
![3](https://user-images.githubusercontent.com/47788955/166211665-9fc2aa73-e46e-493f-94f6-0e799ef6832e.png)
![4](https://user-images.githubusercontent.com/47788955/166213461-5fa50049-df37-4237-94ef-8b7bf81dd8b8.png)

**Comment by jbraese** [comment]
As discussed with the team, we have now removed the wording "Paused" from the UI. Clicking on the old "Stop Tracking" button now opens a modal that asks the user if they want to be notified to turn tracking back on. 

![Screenshot_1652104417](https://user-images.githubusercontent.com/47788955/167427144-2cb532dd-9a0d-46af-8762-c1fe616fec53.png)

![Screenshot_1652104429](https://user-images.githubusercontent.com/47788955/167427134-27e7ff45-ad47-456a-9e09-c3b8a0f3625b.png)
