### ISSUE TITLE
Log events necessary for study

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#197]
Based on https://github.com/sitcomlab/simport-learning-app/issues/179 we can now event based log a variety of parameters in the app. So far, we don't log that many events but might do log more for the study.

- [x] Which events are missing?
- [x] Log those

**Comment by zven** [comment]
- [x] log access to imprint / privacy policy page

**Comment by JuanFFranco** [comment]
Here are the logging events that could be implemented:

- [x] Tracking started
- [x] Tracking stopped
- [x] Location Update
- [x] Background geolocation
- [ ] Settings
- [x] Imprint
- [ ] Licenses
- [x] Settings Privacy policy
- [ ] Record own trajectory
- [ ] Explore trajectories
- [ ] Add own trajectory
- [x] Write your diary
- [ ] Check terms and privacy policy
- [x] Tracking privacy policy
- [x] Explore your trajectory
- [ ] Show notifications
- [ ] Filter insights
- [ ] Filter by home
- [ ] Filter by POI
- [ ] Filter by workplace
- [ ] Filter low
- [ ] Filter medium
- [ ] Filter high
- [x] Map create entry
- [ ] Insights button
- [ ] Map button
- [ ] Timetable
- [ ] Select place
- [ ] Add entry
- [ ] Create entry date
- [ ] Save entry
- [ ] Export diary
- [x] User opens map view
- [x] User leaves map view

**Comment by JuanFFranco** [comment]
I get this error when testing related to the sample trajectories but haven't been able to find a solution. How could I solve them?

![image](https://user-images.githubusercontent.com/76211446/186339284-9eb3f4e0-6a46-4b87-9da2-37ad9dc7d377.png)

**Comment by schrooom** [comment]
> I get this error when testing related to the sample trajectories but haven't been able to find a solution. How could I solve them?
> 
> ![image](https://user-images.githubusercontent.com/76211446/186339284-9eb3f4e0-6a46-4b87-9da2-37ad9dc7d377.png)

This is just our "usual" test-error due to our non-deterministic inference-tests, thus nothing to be concerned about.  :)
