### ISSUE TITLE
background geolocation plugin seems incompatible with capacitor sqlite plugin

### ISSUE THREAD

**Issue by noerw** [sitcomlab/simport-learning-app#2]
iOS builds fail since adding the `@capacitor-community/sqlite` plugin in https://github.com/sitcomlab/simport-learning-app/commit/88146d22745631149e27cb6e5b8e324b30dc3b45 due to incompatibile inclusions of sqlite in that plugin and in `@mauron85/cordova-plugin-background-geolocation`.

![build fail screenshot](https://trello-attachments.s3.amazonaws.com/5efefe6ca1055d38b42c01f8/5f58a4bc2c8297580d770bd2/0fda0a10b9cfb4985ece99be4f032a50/broken_ios_build.png)

Das background geolocation plugin hat die funktionalität daten lokal zu sammeln und in batches an einen server zu schicken. zum cachen der daten nutzt es eine sqlite DB.
Auf android ist standardmäßig schon ein interface zu sqlite systemweit verfügbar, daher gibts jetzt nur auf iOS einen Konflikt mit der anderen sqlite implementierung des sqlite plugins..
Da diese funktionalität für uns schwachsinn ist könnte man drüber nachdenken sie aus dem location plugin rauszuoperieren. Mir fällt grad keine andere option ein, kenne mich aber auch nicht mit dem iOS build process aus, evtl kann man da header umbenennen oder in namespaces stecken um den Namenskonflikt zu vermeiden?

**Comment by noerw** [comment]
~~As I don't have a iOS toolchain ready, maybe my checkin was not correct. Can somebody try to run this and see if there is more to check in? Might also fix the build issue..~~
```
ionic cap sync ios
```

zven confirmed that the issue persists after running `ionic cap sync ios`

**Comment by schrooom** [comment]
Got it working: import of sqlite needs be `#import <sqlite3.h>` instead of  `#import "sqlite3.h"`. Quote marks are for local files, those brackets resemble external files.

I'm not familiar with ionic and its build-process - not sure how/where to integrate this.

**Comment by noerw** [comment]
@jerry1621 Nice! I think the proper way to fix it is to make the change upstream, as `ionic cap sync` will revert our local changes.
I'll do that later

**Comment by noerw** [comment]
Can sombody with XCode check if current `develop` fixes this issue? :)
(you need to rerun `npm install && ionic cap sync ios --no-build`)

**Comment by schrooom** [comment]
Does not seem to work for me - import is remaining at `#import "sqlite3.h"`, even though your changes look good to me. Anything that could be failing on my side?

**Comment by noerw** [comment]
Sorry, I only made a partial fix, now it should have updated.

**Comment by schrooom** [comment]
Perfect, works fine now!
