### ISSUE TITLE
Google App Review Rejection

### ISSUE THREAD

**Issue by felixerdy** [sitcomlab/simport-learning-app#208]
The app got rejected from Google. Below you can see the feedback from Google:

---

__Feedback:__

<td style="padding:10px 10px 15px;font-size:13px;line-height:21px;font-family:Roboto,Helvetica,Arial,sans-serif;color:rgb(74,74,74)" valign="middle">We’ve reviewed your app for compliance with all Location Permissions policy requirements (including use case eligibility), and found the following issues with your app:<br>
<table style="border-collapse:collapse">
<thead>
<tr>
<th style="padding:4px 10px;border:1px solid rgb(204,204,204);background-color:rgb(245,245,245)">Version(s)</th>
<th style="padding:4px 10px;border:1px solid rgb(204,204,204);background-color:rgb(245,245,245);width:85%">Eligibility Issue</th>
</tr>
</thead>
<tbody>
<tr>
<td style="padding:4px 10px;border:1px solid rgb(204,204,204)">App Bundle:1</td>
<td style="padding:4px 10px;border:1px solid rgb(204,204,204)"><strong>Invalid privacy policy</strong><br>Based on our review, your privacy policy doesn’t comply with our policy requirements. Please review the <a href="https://support.google.com/googleplay/android-developer/answer/9888076#personal-sensitive" target="_blank" rel="noopener">Personal and Sensitive User Data</a> policy and ensure that you are compliant.<br><br>Please<a href="https://support.google.com/googleplay/android-developer/answer/113469#privacy" target="_blank" rel="noopener"> add or update your privacy policy</a>. Below is a compliance checklist for privacy policies. Your privacy policy must:
<ul>
<li>Reference <strong>location data</strong> and your app’s use and handling of location data</li>
<li>Clearly label that the page is a privacy policy, for example,&nbsp;listed as "privacy policy" in the title&nbsp;or has “privacy” in the URL and body of the page</li>
<li>Be readable in a standard browser without any plug-ins or special handlers (for example, no PDFs, no uncommon MIME types)</li>
<li>Be available on an active, visible URL</li>
<li>Be non-editable</li>
<li>Refer to your app by name</li>
<li>Be linked on your app's Store listing page and/or within your app</li>
<li>Have a URL that links to a single governing privacy policy in your website and/or Play Store listing rather than one that points to multiple privacy policies&nbsp;</li>
</ul>
Learn more about privacy policy requirements in the <a href="https://support.google.com/googleplay/android-developer/?p=pp-i" target="_blank" rel="noopener">Developer Policy Center</a> or in this <a href="https://www.youtube.com/watch?v=b0I1Xq_iSK4" target="_blank" rel="noopener">video</a>.</td>
</tr>
<tr>
<td style="padding:4px 10px;border:1px solid rgb(204,204,204)">App Bundle:1</td>
<td style="padding:4px 10px;border:1px solid rgb(204,204,204)"><strong>Missing information in prominent disclosure</strong><br>Your prominent disclosure must appear before your app’s location runtime permission, and should tell the user which feature(s) will use location in the background. Based on our review, your app’s prominent disclosure did not meet this criteria.<br><br>Based on our review, your prominent disclosure doesn’t comply with our policy requirements.The language in the disclosure MUST include the following elements:
<ul>
<li>The term “location”</li>
<li>Indication that the nature of usage is in the background by using one of the following phrases “background” / “when the app is closed” / “always in use” / “when the app is not in use”</li>
<li>A list of all the features that use location in the background</li>
<li>If you extend permitted usage to ads, you must include the following: “used to provide ads / support advertising / support ads.” (Choose the most accurate phrasing)</li>
</ul>
<p>To meet the policy requirements, it’s recommended that you reference one of the following example formats, the second example includes the use of location for ads (choose the most relevant phrasing):</p>
<ul>
<li>“[This app] collects location data to enable ["feature"], ["feature"], &amp; ["feature"] even when the app is closed or not in use.”</li>
<li>“[This app] collects location data to enable ["feature"], ["feature"], &amp; ["feature"] even when the app is closed or not in use and it is also used <strong>to support advertising</strong>.”</li>
</ul>
<em>Example: “Fitness Funds collects location data to enable fitness tracking even when the app is closed or not in use.”</em>
<p>The prominent disclosure should not appear alongside other data privacy disclosures or as part of the privacy policy. The prominent disclosure also should not contain contradicting or unclear information.</p>
<p>Please modify your prominent disclosure and make sure to include the updated prominent disclosure in the video required in the Developer Console as part of the in-app experience.</p>
Learn more about prominent disclosure requirements in the <a href="https://support.google.com/googleplay/android-developer/?p=pd-i" target="_blank" rel="noopener">Developer Policy Center</a> or in this <a href="https://www.youtube.com/watch?v=b0I1Xq_iSK4" target="_blank" rel="noopener">video</a>.</td>
</tr>
</tbody>
</table>
</td>

---

__Todos:__

- [x] make app privacy policy publicly available via website or markdown page on github: subpage on simport website -> link from app and also from google play store => https://simport.net/learning-app-privacy-policy/
- [x] find out missing information in prominent disclosure -> What is that? In app view or Android permission dialogue?
- [x] update information text if needed
- [ ] recreate explanatory video
- [ ] submit `study-1` version for review

**Comment by felixerdy** [comment]
Regarding privacy policy: we might need to upload our current privacy policy to public available website which we can link in the google play console

**Comment by schrooom** [comment]
> Regarding privacy policy: we might need to upload our current privacy policy to public available website which we can link in the google play console

Could we simply put it into the repository as a markdown-file?

**Comment by felixerdy** [comment]
> > Regarding privacy policy: we might need to upload our current privacy policy to public available website which we can link in the google play console
> 
> Could we simply put it into the repository as a markdown-file?

Yes we could give that a try. Otherwise, we could simply run the web version of the app on something like [netlify](https://www.netlify.com/) and link the privacy policy page.

**Comment by zven** [comment]
Just to clarify: The version that has been reviewed was a manually uploaded `develop` and not the state as we would like to use for the study, right?

**Comment by zven** [comment]
- [x] upload and link privacy policy
- [ ] missing information in prominent disclosure -> What is that? In app view or Android permission dialogue?

**Comment by zven** [comment]
@felixerdy I added and updated the discussed todos to the description of this card.

**Comment by felixerdy** [comment]
This video describes what needs to be included in the privacy policy and in the prominent disclosure: https://www.youtube.com/watch?v=b0I1Xq_iSK4. Additional information can be found here: https://support.google.com/googleplay/android-developer/answer/9799150?rd=1#prominent_disclosure&zippy=%2Cschritt-deutliche-offenlegung-innerhalb-der-app

There is also an example text how the disclosure text could look like: „[Diese App] erhebt Standortdaten, um [„Funktion“], [„Funktion“] und [„Funktion“] zu ermöglichen, auch wenn die App geschlossen ist oder nicht verwendet wird.“ 

I'll add the text to the corresponding page on a new branch

**Comment by felixerdy** [comment]
I just updated the prominent disclosure with more information about the use of location information. You can also find a video here: #211
