### ISSUE TITLE
Investigate energy consumption issue on Android devices

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#209]
One of the participants of the try run reported that the app drained the battery so fast that they stopped the tracking.

**Comment by thierna** [comment]
Participant said: Battery was drained much faster as usual.
OnePlus 6 (Model A6003) Phone
Android version 11
OxygenOS version 11.1.2.2

removed app from battery optimization settings for better tracking
allowed permissions: files and media, location

**Comment by zven** [comment]
To investigate this issue, I suggest we use the `study-1` branch as a baseline and compare different conditions:

1. no changes
2. no inference computation
3. no background tracking
4. no tracking and no inference computation 

This is just some ideas. Comparison between 1. and 2. might be the most interesting.

**Comment by JuanFFranco** [comment]
Case 1: Ran for 9:24 hours and the app represented 4.65 % of battery consumption, being the app that consumed the most in my phone

![Screenshot_2022-07-15-15-37-58-178_com miui securitycenter](https://user-images.githubusercontent.com/76211446/179235033-5b361af1-b08b-4bcc-b725-12a07a513275.jpg)

Case 2: Ran for 9:25 hours and got a similar behavior in the battery consumption, although the app is not listed within the first apps that consume more energy. This time consumes a little less than first case, 3.27%.

![Screenshot_2022-07-19-16-19-30-522_com miui securitycenter](https://user-images.githubusercontent.com/76211446/179908882-935a6bf3-143b-44d8-bb2e-9d4a33f27b3d.jpg) ![Screenshot_2022-07-19-16-19-09-642_com miui securitycenter](https://user-images.githubusercontent.com/76211446/179908884-dc5ca0dd-9622-46a8-9052-178169010393.jpg)



Case 3: No relevant energy consumption related to the app registered in the battery consumption tracking 

Case 4: Same as case 3

**Comment by zven** [comment]
@JuanFFranco What is the setup for Case 3? Did you simply turn off location tracking in the app (= via the interface) or did you change sth. in the code and recompiled the app?

**Comment by JuanFFranco** [comment]
@zven I just did it from the app, no changes in the code. And for case 2 that I'm running right now, I found a constant defining the time interval when the inferences are made and changed it for a really big one, and now I'm seeing some differences in the performance already.

**Comment by zven** [comment]
Verdict: It seems like the energy consumption is mainly caused buy the background tracking and not by our inference computation.
