### ISSUE TITLE
Start stop tracking UI behaviour broken

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#213]

**Comment by JuanFFranco** [comment]
The UI is not behaving properly in the start/end button along with the `terms and privacy policy` checkbox.

-The `start/end` tracking button is showing the icon inverted (play when should be stop and vice versa):

![Screenshot_20220704_213121](https://user-images.githubusercontent.com/76211446/177209587-fe898009-a1ee-4b27-b898-5a66ae63f65f.png) ![Screenshot_20220704_213052](https://user-images.githubusercontent.com/76211446/177209594-16b808f5-1d24-42b5-8c87-aa88c0255a15.png)

-The tracking should not be possible wen there's no agreement with the `privacy policy`. The old behavior was that when the user wants to uncheck the box and the tracking is active, it shows a modal to confirm, and if affirmative, the tracking would be automatically stopped.

![Screenshot_20220704_213136](https://user-images.githubusercontent.com/76211446/177209758-20a146bc-668d-4003-b105-35ef8fad90f0.png)
