### ISSUE TITLE
Experiment with tracking accuracy

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#214]
At the moment, we are discarding location updates with an accuracy value greater than 50 meters. Although this leads to higher quality of the data we actually collect, we might also miss out those situations where tracking and accuracy is less than ideal and thus not collect any data at all (e.g. in the train).
Task: Investigate results with different accuracy values (e.g. in the train and/or in the bus).

**Comment by zven** [comment]
Since this issues was reported from one of the pre-testers on Android, I'd suggest that we do the testing and adjustment of the accuracy on Android first. In addition, this especially have seemed to be an issue while being on a train, where suddenly almost no locations where recorded (although it is not entirely sure where this issue stems from: No GPS signal because the phone was shielded from above? Movement too fast? Lack of nearby wifi networks for positioning? Switching between mobile network cells too fast?).

One first step would be to use the app (and potentially also do a short train ride or something similar) and compare the tracking behaviour with different accuracy settings (e.g. 50, 100 and 200 meters).

**Comment by JuanFFranco** [comment]
- Accuracy 10m:

![Acc_10m](https://user-images.githubusercontent.com/76211446/182441434-c74204c9-25b5-49c2-8286-26e6adcec666.jpg) 
![Web capture_2-8-2022_20933_developers google com](https://user-images.githubusercontent.com/76211446/182444418-1e7a9a9c-1008-4ab5-a2f2-e7f7e3b92a7b.jpeg)

- Accuracy 50m:

![Acc_50m](https://user-images.githubusercontent.com/76211446/182441477-1c8dd463-6cdf-423a-a7a0-e8f2c1f172b4.jpg) 
![image](https://user-images.githubusercontent.com/76211446/182444707-fc6cfc00-d421-49a5-88ad-00b146725481.png)

- Accuracy 100m:

![Acc_100m](https://user-images.githubusercontent.com/76211446/182441559-15d1ecd6-d480-4064-9e2f-8a6af6b5a50b.jpg) 
![Web capture_2-8-2022_20719_developers google com](https://user-images.githubusercontent.com/76211446/182444051-ade32534-cbb9-48be-8789-f44aca8cc704.jpeg)

**Comment by zven** [comment]
Since there does not seem to be much difference (or at least no significant gaps while tracking with a rather hard accuracy threshold of 10 m compared to the other settings), this does not seem to be the issue here.
