### ISSUE TITLE
Adjust privacy policy + imprint to feature set

### ISSUE THREAD

**Issue by jbraese** [sitcomlab/simport-learning-app#220]
Currently, privacy policy and imprint always describe the behaviour/goal of the fullly featured app. When an alternative mode (e.g. no inferences, only diary) is turned on, they thus contain app functionality that will not occur. This might confuse users and could, in a study setting, impact the integrity of control mechanisms.

**Comment by thierna** [comment]
Comparing the website version, the long privacy policy version on beemo and the in-app version - there were some differences:
- App and Website name two different persons to contact for questions (Sven / Chris)
- App and Website name differently who to contact at university - Stabsstelle Datenschutz in App, Online Meyer-Pachur
- in App policy says that deleting the app will delete the data, but can only delete data that is stored locally ?
- Mention of study is missing in app policy version
- Mention of project partners is missing in app policy version
- App policy claims that anonymisation will make it impossible to re-identify people. --> but re-identification is technically possible...

**Comment by zven** [comment]
What we track on this card:

- [ ] update privacy policy in app
- [ ] update privacy policy linked from app store description
