### ISSUE TITLE
Update app privacy policy

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#224]
Based on the input of the data protection office of the WWU we reworked the privacy policy: https://nextcloud.beemo.eu/f/6068
The updated privacy policy for the app _and_ study can be found here: `DSE_SIMPORT_en.docx`. I tried to extract only those parts that are relevant for the app (= leaving out the study parts) in this document: `updated_privacy_policy_for_app.txt`. Please do also double check if the current privacy policy that is already in the app contains any additional information that is not covered the txt file.

**Comment by JuanFFranco** [comment]
The information extracted from the docx file looks good. Nevertheless, here the topics that I found on the old text in the app that are not mentioned in the new text:

- The text mentions that the app stores the location information inside the users' device but does not mention about storing the timestamp for each point, as it is in the second paragraph of current text.
- In the txt file is not mentioned that the app could identify sensible data as "home" or "workplace" and label it, as it appears in the old text in the first paragraph of `Usage of your data`.
- The new text mentions all the process on how gets the CARTO information, but not the reverse geocoding (Third paragraph of `Sharing or disclosure of information`.
- I guess the section of `Changes to the privacy policy` should be also added.
