### ISSUE TITLE
Fix firebase distribution

### ISSUE THREAD

**Issue by schrooom** [sitcomlab/simport-learning-app#228]
Our current firebase distribution method doesn't work anymore. It looks like it fails because of the authentication method.

```
Authenticating with `FIREBASE_TOKEN` is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS`: https://cloud.google.com/docs/authentication/getting-started
[...]
Error: failed to upload release. Failed to make request to https://firebaseappdistribution.googleapis.com/upload/v1/projects/***/apps/***/releases:upload
```
(→ [see here](https://github.com/sitcomlab/simport-learning-app/runs/8229427204?check_suite_focus=true))

**Comment by felixerdy** [comment]
This issue is now finally resolved after setting the right permissions to the application credentials file in the Google Cloud Console. See https://github.com/sitcomlab/simport-learning-app/actions/runs/3128952322/jobs/5088664477
