### ISSUE TITLE
Last trajectory segment never displayed on map

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#229]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-09-08 at 12 02 21](https://user-images.githubusercontent.com/2930332/189097078-9be73e1d-37b4-4875-9622-1fe20dbd0db4.png)

![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-09-08 at 12 15 16](https://user-images.githubusercontent.com/2930332/189097421-b1e1f7ed-6350-4efa-8989-e1ecf3b86e1f.png)

**Comment by JuanFFranco** [comment]
When drawing the trajectory, the last location was being ignored, so the segment was not taken into account. I just changed one < for a <= and apparently it works without drawing the straight lines that we wanted to avoid in the first place.

![Screenshot_20220909_143113](https://user-images.githubusercontent.com/76211446/189350813-4ea04279-7352-4c62-9e8e-175a9b6c08d9.png)  ![Screenshot_20220909_143120](https://user-images.githubusercontent.com/76211446/189350822-cb9cade9-429d-42a5-ac42-9127ec1a0131.png)
