### ISSUE TITLE
Re-create study setup

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#235]
Since the pre-study revealed that the automatic tracking on Android is rather unstable and tends to stop after approx. 1 day (see https://github.com/sitcomlab/simport-learning-app/issues/233) and the UI state of the tracking button does also not seem to reflect the current tracking state (see https://github.com/sitcomlab/simport-learning-app/issues/234).

To reproduce the issue and get a better understanding of what might went wrong, each team member should try to re-recreate the study setup:

- install the app from the `study1` branch that is distributed via the Google Play Store.
- start the tracking, de-activate energy saving settings for this app and allow background tracking
- make an entry to the journal every evening for seven days and observe if location has actually been updated during that day on the map
- export your diary

**Comment by thierna** [comment]
The tracking active notification text is unclear.  Could be shortened?

![notification text unclear 2022-09-26 ](https://user-images.githubusercontent.com/7602648/192745749-6b0682c4-1bdb-4d08-a07e-47257e65528f.jpg)

**Comment by thierna** [comment]
Button to show location / hide location in map view has unclear wording. Should be zoom in to your current location ?

Debug information screen is empty?

**Comment by thierna** [comment]
looking at the example map for the first time produces an empty map as loading takes some time 
![Screenshot_20220926-173218](https://user-images.githubusercontent.com/7602648/192748237-18ce94c2-b077-4393-9085-cf3972653405.png)

**Comment by zven** [comment]
Obsersvations made by @JuanFFranco regarding the tracking behaviour: https://github.com/sitcomlab/simport-learning-app/issues/234#issuecomment-1259957642

Excerpt from comment mentioned above:

- When staying in the same place for a long time (for example at the office or overnight), the tracking stops automatically.
- Some cases when losing signal for a while, for example while in the U-Bahn, the tracking stopped, but not every time (probably has a time tolerance?).
- When tracking is activated and phone turns off, the tracking stops automatically (for example when battery dies and charging the phone again).
- In all cases, autostart in app configuration settings was disabled too. (Could it be that because for external reason, like phone turning off, the user started the tracking again but forgot to set the autostart on again?

**Comment by zven** [comment]
First conclusion of my tests:
- Tracking needs to be restarted after approx. 3 days on both devices (see below)
- seems to stop after being longer in one place -> home or work location

Nexus 5:
- 25.09. - 29.09 (Sunday to Thursday)
- location stuck on home location on Wednesday morning, one restart needed -> needed to hit stop button multiple times until it actually stopped (at least UI wise)

Galaxy:
- 25.09. - 29.09 (Sunday to Thursday)
- tracking has stopped on Wednesday night -> ride to work and everything afterwards not recorded

**Comment by zven** [comment]
For @thierna and @jbraese the tracking seemed to be stable for multiple (how many?) days in a row, right?

**Comment by jbraese** [comment]
On my phone with battery optimization turned off, tracking works until a) either the phone has very low battery or b) it shuts off due to low power. In case a), the tracking stops but the button still shows it as running. In case b), the tracking stops and the button correctly shows it as stopped.

**Comment by thierna** [comment]
Tracking worked from 6.10.-9.10. no location recorded on 10.10. In app overview it says "Dein Standortverlauf" 5 Tage - so it seems at least the day counter is running.

**Comment by zven** [comment]
Let's see if the old or the new library (see here: https://github.com/sitcomlab/simport-learning-app/issues/239) performs better, then.
