### ISSUE TITLE
preview of diary entries cuts short in middle of screen - preview could be longer?

### ISSUE THREAD

**Issue by thierna** [sitcomlab/simport-learning-app#238]

**Comment by thierna** [comment]
![Diary-entry-preview-truncated](https://user-images.githubusercontent.com/7602648/192745541-d5ea8812-6c1a-41dc-a586-6fc42ae61d2f.jpg)

**Comment by JuanFFranco** [comment]
Set height of card min to 90px and max to 145 px


![Screenshot_2022-10-19-05-03-08-844_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/196587607-ec5e6405-5495-42c3-88f5-a7a3879344f8.jpg)

**Comment by JuanFFranco** [comment]
Added ellipsis at the end of the line. Just one line though

![Screenshot_2022-11-02-05-15-46-926_de ifgi simport learning](https://user-images.githubusercontent.com/76211446/199394578-16ed6575-35c0-42b2-8dd2-597c0947d596.jpg)
