### ISSUE TITLE
Log when and how many POIs are computed

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#245]
As part of the deployment study, POIs based on their collected data will be shown to the participants. To ensure afterwards that this has actually happened, we need to log when and how many POIs are computed.

**Comment by JuanFFranco** [comment]
Created log that shows when inferences were computed, automatically or manually, and shows for which trajectory.

![image](https://user-images.githubusercontent.com/76211446/200766073-1e659e9d-7885-4ee7-a152-b66e161c5ff0.png)
