### ISSUE TITLE
Fix GitHub Action warnings

### ISSUE THREAD

**Issue by felixerdy** [sitcomlab/simport-learning-app#248]
After running the [Google-Play-Android-Distribution](https://github.com/sitcomlab/simport-learning-app/actions/runs/3320103440) several deprecation warnings appeared: 
- Node.js 12 actions are deprecated
    - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- The `set-output` command is deprecated and will be disabled soon
    - https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

We should check and update the packages we are using in our Actions

**Comment by felixerdy** [comment]
Actions using Node.js 12

`General`
- https://github.com/coturiv/setup-ionic (no newer version available)
- https://github.com/actions/setup-node (v2 -> v3 available)

`Android`
- https://github.com/nttld/setup-ndk (v1.0.3 -> v1.2.0 available)
- https://github.com/actions/setup-java (v1 -> v3 available)
- https://github.com/chkfung/android-version-actions (v1.1 -> v1.2.1 available)

`iOS`
- https://github.com/yukiarrr/ios-build-action (no newer version available)

**Comment by zven** [comment]
Remarks

* Github-Actions with node12?
* alternative library for building on iOS
