### ISSUE TITLE
short test run with study1 branch

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#252]
- fresh installation from Google Play (in case you don't have access to it, send @zven a message)
- access all pages: Any glitches?
- start tracking: Does permission process / dialogue work?
- let run for some time
- Does data show on map?
- Diary entries: Do they work?
- Does tracking run for some time in the background?
- Does pause feature work?
- Does export feature work?

**Comment by thierna** [comment]
I am able to start the tracking without having to chose the accepting the privacy policy checkbox myself?

Steps to reproduce
- Install from google play https://play.google.com/store/apps/details?id=de.ifgi.simport.learning
- Click on Standortverlauf
- Click on Aufzeichnung starten 
- PopUp of Privacy Information
- Okay marks the checkbox for privacy policy
- Android PopUp to allow tracking permission (default is only while using the app)
- Have to allow for always in the settings
- Tracking is not started but have to click on starten again
- Tracking is active

**Comment by thierna** [comment]
Steps to export - Sharing option throws errors if chosing to share with messengers
- Click on Standortverläufe
- Click on the ... Chose - Teilen (Sharing with messengers)
- both whatsapp and threema do not accept json files
- Download option requires permissions

--> Steps for exporting the json need to be really specific so participants can follow them
