### ISSUE TITLE
Check: How much do study1 and develop branch deviate?

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#270]
- [x] create tag for current `study1` branch state
- [x] create overview of deviations
- [ ] merge into develop branch or simply leave `study1` branch as it is?

**Comment by jbraese** [comment]
The state of the app used in the first deployment study is accessible via the tag "study1" (https://github.com/sitcomlab/simport-learning-app/tags). 

Features in branch `study-1` that are not in `develop`:
- add building .apk with Github actions
- set default feature flags to those used in the study
- change to the privacy policy noting that only in one of the two app modes (i.e. not control group) location data is saved locally to the device
- change to the imprint removing a text describing the purpose of the app.

The changes to the feature flag and the privacy policy/imprint will need to be adjusted for any new study. Having the ability to build the .apk through Github Actions seems useful though.

**Comment by zven** [comment]
Okay, I'd then suggest to cherry pick the Github actions  into the develop branch (and don't merge the whole `study1`-branch into the `develop` branch).

**Comment by jbraese** [comment]
While doing this, I noticed that both android and iOS builds are currently failing on develop. It seems to be an issue with the action we use to setup ionic (https://github.com/coturiv/setup-ionic/issues/19 - thanks to @felixerdy for the tip). I tried adding a step to manually install capacitor as suggested there, but so far it still fails (when manually triggering actions you can choose the branch from which to run it). 

Here is the branch if anyone can take a look: https://github.com/sitcomlab/simport-learning-app/tree/feature/build-apk-with-action

**Comment by schrooom** [comment]
> While doing this, I noticed that both android and iOS builds are currently failing on develop. It seems to be an issue with the action we use to setup ionic ([coturiv/setup-ionic#19](https://github.com/coturiv/setup-ionic/issues/19) - thanks to @felixerdy for the tip). I tried adding a step to manually install capacitor as suggested there, but so far it still fails (when manually triggering actions you can choose the branch from which to run it).

I had a look into this: The current Ionic CLI (Version 6.20.8) in connection with our Capacitor version is the cause for the failing builds. Fortunately the problem is exclusively occurring with older Capacitor versions – the [update to Capacitor 4](https://github.com/sitcomlab/simport-learning-app/issues/268), which we're currently working on, seems to resolve this issue.

Therefore I'd suggest to ignore it for now, it'll be fixed soon-ish :)

**Comment by zven** [comment]
I agree. If the problem is solved with the capacitor update, we can ignore it for now. 👍
