### ISSUE TITLE
Create .apk file on develop branch in github actions

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#277]
This was a feature we implemented on the `study1`-branch and could have been cherry picked into `develop` as part of this card: https://github.com/sitcomlab/simport-learning-app/issues/270

Since the github actions are currently failing due to capacitor issues, we'll actually merge or implement this feature once the capacitor update (see here https://github.com/sitcomlab/simport-learning-app/issues/268) is done.

**Comment by felixerdy** [comment]
This has been done in 3f32d6e459f68fc925643304eb161ed282960191
