### ISSUE TITLE
Internal release of capacitor 4 version

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#280]

**Comment by thierna** [comment]
Comments from internal testing 
- copyright date 2022 - needs to be 2023 ?
- mixing Du in the app with Sie in the policies ?
- create different notifications for example data and personal data - Rückschlüsse aus deinen Daten (but its from the example data ?)
- calculating inferences on the test data - takes long and then says no inferences to display ?

![lade-rueckschluesse](https://user-images.githubusercontent.com/7602648/220947135-26402891-70d4-43ab-9196-bd85b06eecd4.jpg)
![keine-rueckschluesse](https://user-images.githubusercontent.com/7602648/220947140-442f3055-8249-4383-80be-da848415186e.jpg)
