### ISSUE TITLE
fix formatting of exported diary file

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#285]
There is a number of issues with the formatting of the exported diary file:

- column delimeter is a `,` which is not ideal given that the diary may contain this character as well
- line breaks in the text section are not handle properly

**Comment by schrooom** [comment]
- Delimiter is left at `,`, but the content is enclosed with `"`, which makes it readable for Excel/Numbers.
- Linebreaks are replaced with tabstops, as Excel interprets them as an indicator for new csv-lines.
