### ISSUE TITLE
Pin lock for app access

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#288]
Since the data we are storing is augmented with inferences about their daily lives, protecting the participants data becomes more important.
Hence, we'll add a pin code feature that the user needs to enter whenever they are accessing their trajectory data. This pin code will also be used for encrypting the database.

Tasks:

- [ ] research: Are there libraries we can use for this? Maybe even something that uses the biometric lock security features implemented in modern phones?
- [ ] implement pin lock feature (based on research above) and use the pin code to encrypt / decrypt the database

**Comment by felixerdy** [comment]
While working on #287 I found the [Biometric Authentication](https://github.com/capacitor-community/sqlite/blob/master/docs/Biometric-Authentication.md) feature of the database driver which is used to secure the secret of the database. After an initial test, the biometric authentication gets triggered on cold app launch. We still need to think about what should happen when:
- The app is launched from the background (not cold launch of app)
- There is no biometric sensor available
- When the biometric authentication is not successful

**Comment by felixerdy** [comment]
In 635a828623ced684162d1133a4a5712791d73f93 I added an initial biometric authentication using the https://github.com/aparajita/capacitor-biometric-auth package
- When the App starts (from cold boot), we are checking if biometric auth is available
    - If no, an alert gets triggered which tells the user to enable biometric auth. The app is then usable as usual
- When biometric auth is available, we try to authenticate the user
    - If authentication is not successful, we are showing an alert all the time which makes the app not usable.
- When authentication was successful, the user can use the app as usual

Note: The authentication request does not trigger when the app was running in the background

TODO: 
- Update texts / alerts
- Handle failed authentication more elegant
- Lock app when in background
