### ISSUE TITLE
Research on Trajectory Storage

### ISSUE THREAD

**Issue by noerw** [sitcomlab/simport-learning-app#3]
In the app, we need to

- store (possibly long) spatial timeseries
- do efficient spatio-temporal queries on them
- (run aggregated statistics on the result)
- on multiple environments / operating systems
- have privacy preserving storage

We need some tech that fulfills these properties. browser `localStorage` is probably not sufficient, although it may work for a first prototype.

**Comment by noerw** [comment]
After some quick research I came to these results:

- [spatialite](https://www.gaia-gis.it/fossil/libspatialite/index) (an postgis-like sqlite extension) is a good fit.
  - there are patches that make it available on mobile platforms: [android](https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki/Android_5.0.0.mk) (well maintained), [iOS](https://github.com/smellman/libspatialite-ios) (not so well maintained)
- for integration of sqlite into ionic/capacitor, there is a [ready-made plugin](https://github.com/capacitor-community/sqlite)
  - it is based on [sqlcipher](https://github.com/sqlcipher/android-database-sqlcipher), a sqlite extension supporting encryption
  - to make it work with spatialite, [some work from us would be required](https://github.com/capacitor-community/sqlite/issues/45).
  - we need to check the [requirements of inference strategies](https://trello.com/c/Mz3iByLW) to see if this fast-to-get-started-lib (without spatial) can work for our prototype
- h2 should be [possible as well](http://h2database.com/html/tutorial.html#android), though there is almost no docs on integrating that into mobile apps.
- if we loosen the requirement of data-remains-with-users device (i don't see that happening..?) plenty other options become available. this is feasible with proper data encryption only, and might be a good test-case for our LP-preserving UI components lateron

We might want to ask jerome or felix if they have used tech with similar requirements before.

**Comment by noerw** [comment]
I now have an initial implementation for sqlite using the existing capacitor plugin.
It works, but it's not great, so we may want to reconsider.
https://github.com/sitcomlab/simport-learning-app/commit/88146d22745631149e27cb6e5b8e324b30dc3b45

**Comment by zven** [comment]
Problem with iOS build:

<img width="879" alt="broken_ios_build" src="https://user-images.githubusercontent.com/2930332/96572031-a6713f00-12cc-11eb-9da0-0462c8a28b46.png">

Since the background geo location brings its own sqlite version for storing locations before they are potentially send out to somewhere via http, it conflicts with the sqlite plugin that we use to store the trajectories.

@noerw suggested to fork the background geo location plugin and remove this unused feature to solve the conflict.

**Comment by noerw** [comment]
@zven see #2
