### ISSUE TITLE
Adjust filter view

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#302]
There used to be two inference filters in the app:

- one on the inference page and one on the map page (not connected but same functionality)

With https://github.com/sitcomlab/simport-learning-app/issues/291 the filter on the inference page has been made obsolete and only the one on the map page is left. Atm, one can toggle the three different categories and filter for inferences with low, medium or high probability (whereas those categories are somewhat artificial).

Some ideas (and implications) for how we could change the filter on the map:

- leave it out (= no filter option) -> result: map might end up quite cluttered and some inferences, e.g. home and work might overlap each other (and thus might not be visible)
- leave it as it is -> issue: three categories imply some certainty / probability that we actually don't have
- replace categories with sliders
- add an info button that explains the probabilities
- remove probability selection but only add the option to toggle inference categories on and off -> remove overlap between categories but map might still be very cluttered

**Comment by zven** [comment]
Update: Match inference quality icons that are used in the inference list (see here https://github.com/sitcomlab/simport-learning-app/issues/291 and here https://github.com/sitcomlab/simport-learning-app/issues/305) to the filter options ("Filtern nach Wahrscheinlichkeit: gering / mittel / hoch"):

![Simulator Screenshot - iPhone SE (3rd generation) - 2023-05-10 at 13 34 25](https://github.com/sitcomlab/simport-learning-app/assets/2930332/c3a61873-f527-4b47-8644-0a549bdeecd2)

**Comment by schrooom** [comment]
Should we do this with or without the labels?

<img width="250" src="https://github.com/sitcomlab/simport-learning-app/assets/17469296/4eee99e0-0065-47c2-8084-c73195cd319c">
<img width="250" src="https://github.com/sitcomlab/simport-learning-app/assets/17469296/93591853-cda7-4bf1-b65a-381a2d0d1051">

**Comment by zven** [comment]
I would tend to the one with the labels.
