### ISSUE TITLE
Check current dev state: Is feature set complete?

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#303]
Check if current state is complete for the study:

- [ ] map view
- [ ] diary + export
- [ ] Are inferences computed?
- [ ] Do reminders work?
- [ ] Reverse geocoding works?
- [ ] Are notifications fired?
- [ ] predictions are not shown and displayed
- [ ] no trajectory in- and export
- [ ] no control group feature

**Comment by felixerdy** [comment]
This was done in 005dc587ffb018c42f4227f8edbb24f127d5b5c1

I didn't wanted to create a PR yet because the `study` branch is not up to date and the `feature/study-feature-flags` branch would merge all the new commits from the `develop` as well

**Comment by zven** [comment]
@felixerdy Then I'd suggest to first review the changes, merge them into the develop-branch and then update the study branch based on the develop-state. Or did you have something else in mind?

**Comment by zven** [comment]
Current state is merged into the `study` branch and currently tested.

**Comment by zven** [comment]
Findings:

- We still have a toggle notifications-slider in the tracking view. To my understanding, that toggle only activates the location update notifications (new notification for each location update) and should be removed.
- In the map view, there is still a "toggle inference" button on the map: Should we remove that button?
