### ISSUE TITLE
Update inference quality indicator

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#305]
Each inference does currently have a progress bar that is completely filled once our internal value for the inference quality reaches 1 (value between 0 and 1). This could communicate some kind of probability as in "Now the app is 100 % sure where you live." Since we can't really be entirely sure here, we adjust this visualization slightly:

The progress bar indicator should never fill up completely but the last 10 % of the progress bar should stay empty (to indicate that the app can never be 100 percent sure).

**Comment by felixerdy** [comment]
Closed in #311
