### ISSUE TITLE
Cluster inference markers

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#306]
Map view: Inferences that are based on the same staypoint cluster currently overlap each other (marker and polygons). In order to see those hidden markers, the user would need to manually toggle the different inference types in the filter view.

Hence, we cluster the inference markers. Details

- cluster distance is set to something small (2 to 5 px): Only those markers that directly overlap are clustered
- the underlying polygons related to the inferences are simply colored gray

**Comment by schrooom** [comment]
To be discussed:

- convex vs concave hulls for inferences?
- smooth hulls with splines?

**Comment by felixerdy** [comment]
Closed in #311
