### ISSUE TITLE
research: When do we toggle notificaitons?

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#319]

**Comment by schrooom** [comment]
Currently the following notifications are fired:

- Location Service
  - Tracking started `location.service.ts:225`
  - Tracking stopped `location.service.ts:239`
  - New location `location.service.ts:191`
  - Unpause tracking message (after pausing tracking for defined time) `tracking.page.ts:169 -> location.service.ts:151`
- Inference Service (only these are toggleable via FeatureFlag `isNotificationsEnabledForInferences`)
  - Generated more than 0 inferences with medium confidence (while in background) `inference.service.ts:193 -> .. -> inference.service.ts:260`
  - Generated more than 0 inferences with medium confidence (user-initiated) `map.page.html:53 -> .. -> inference.service.ts:260`
- Timetable Service
  - Prediction of next visits (while in background) `timetable.service.ts:98 -> .. -> timetable.service.ts:70`
