### ISSUE TITLE
Filter on map: No text for English translation?

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#320]
On `study` branch

**Comment by schrooom** [comment]
Works for me for both, Android and iOS in german and english.

**Comment by zven** [comment]
Curious! It also seems to work on the old Nexus 5 device. So far, it does only seem to occur on the Pixel 6 device.

@jbraese Have you also encountered this issue?

**Comment by jbraese** [comment]
I do see text on my app, see the attached image.

**Comment by schrooom** [comment]
Could this be a layout issue for some devices? Meaning the text is there, but out of sight (outside of view, or white on white?)
