### ISSUE TITLE
Inferences: Design Testcases & gather data

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#34]
- [x] Load .gpx files for home location, commute to work, work location, commute back home
- [x] Create staypoint clusters for home and work location
- [x] Add temporal information
- [x] Export whole trajectory as .csv
- [x] Export whole trajectory as .json
- [x] Export whole trajectory as .gpx
- [x] Check in .gpx files and load them as default
- [x] Save output to `test-data` folder in `inferences` directory
- [x] Create separate trajectories with properties that are expected in tests
- [x] Run test-creation via `npm test`
- [x] Load trajectories from .json files in tests

**Comment by zven** [comment]
Execute script on Mac: `npx ts-node generate_test_trajectory.ts`

**Comment by schrooom** [comment]
Note: comment/question in 371205d
