### ISSUE TITLE
Export / import trajectories

### ISSUE THREAD

**Issue by schrooom** [sitcomlab/simport-learning-app#37]
- [x] Enable access to filesystem
- [x] Export trajectories
  - [x] update UI to enable users to export trajectories
  - [x] iOS
  - [x] Android
- [x] Import trajectories
  - [x] iOS
  - [x] Android
~~- Evaluate imports to DB vs .json-files to filesystem~~ (low priority for now)
- [x] Unit tests

**Comment by noerw** [comment]
@schrooom On `feature/inference-testing` branch I extracted the JSON parsing logic into `Trajectory.fromJSON()`, which you might want to build upon.
