### ISSUE TITLE
Trajectories are replaced rather than expanded

### ISSUE THREAD

**Issue by schrooom** [sitcomlab/simport-learning-app#38]
When tracking your own location while already having a recent trajectory, that trajectory gets replaced by a new one rather than expanding the recent trajectory with new recorded locations.

**Comment by noerw** [comment]
Couldn't reproduce this previously on android, I'll test today with current `develop` to see if it's an iOS sqlite quirk

**Comment by noerw** [comment]
Idea: this might be a regression of the recent addition of `ON DELETE CASCADE` to points table in 57b553ed68c0c0b97e5229c27ec1450142fcea9b:
https://github.com/sitcomlab/simport-learning-app/blob/57b553ed68c0c0b97e5229c27ec1450142fcea9b/src/app/shared-services/db/migrations.ts#L71
 in combination with `INSERT OR REPLACE` on trajectory?
https://github.com/sitcomlab/simport-learning-app/blob/57b553ed68c0c0b97e5229c27ec1450142fcea9b/src/app/shared-services/db/sqlite.service.ts#L89

edit: can reproduce on android

**Comment by schrooom** [comment]
This was my conclusion just now too. Changing the `INSERT OR REPLACE` to `INSERT OR UPDATE` does the trick.

**Comment by noerw** [comment]
fixed by #39

**Comment by schrooom** [comment]
Unfortunately this did not work as well as it seemed - now new trajectories aren't properly inserted. Working on another fix just now.
