### ISSUE TITLE
As a User I want to be able to use the app with my own realtime location data

### ISSUE THREAD

**Issue by noerw** [sitcomlab/simport-learning-app#5]
- [x] Persistence: actually store locations
- [x] long/midterm background runtime testing on android
  - initial tests on nexus 5 indiciate that location updates stop after a while.

**Comment by noerw** [comment]
Further testing on the Nexus 5 shows that once battery-optimizations are disabled for the app, the background task is working *most of the time*.
So it's not entirely stable, but in a usable state. This statement is backed with N=1 ;)

**Comment by zven** [comment]
![iOS_broken_map_zoom](https://user-images.githubusercontent.com/2930332/99086793-4e2b1580-25ca-11eb-9f74-2603f64f7f14.png)

When you open the app on iOS and then select the Nepal example before any other trajectory, zooming to the trajectory seems to be broken.

**Comment by noerw** [comment]
implemented in #14
