### ISSUE TITLE
As a User I want to delete my data

### ISSUE THREAD

**Issue by noerw** [sitcomlab/simport-learning-app#6]

**Comment by felixerdy** [comment]
Initial implementation in 0e86ef4025d5f9cdf1eb01ce9d16d59eabb853e7

| Trashcan besides user trajectory | Alert promt |
| - | - |
| ![Screenshot_20210204-135654](https://user-images.githubusercontent.com/12086004/106899680-f1855580-66f5-11eb-92c5-0e0a9608d415.jpg) | ![Screenshot_20210204-135700](https://user-images.githubusercontent.com/12086004/106899697-f6e2a000-66f5-11eb-87d4-d34c70ca69c5.jpg) |

TODO:
- [x] Update list of available trajectories after delete
- [x] Stop current recording of trajectory if user wants to delete it
