### ISSUE TITLE
Android: tracking with low & unstable point density

### ISSUE THREAD

**Issue by noerw** [sitcomlab/simport-learning-app#71]
On Android current position updates are very irregular:

- update frequency averages at around 620s, but not really regular
- update frequency (?) unrelated to traveled distance, direction
    - during a local trainride, a new update is emitted on every second stop..?!
- updates stop at some point after the background task was started (irregular, after 2h - 2days)

I see 4 possible causes:
- the locationProvider we use (default `DISTANCE_FILTER_PROVIDER`) does not work properly on android
- the locationProvider we use needs to be configured differently on android
- the background-process scheduling on these devices is too aggressive, killing the web view running our app
- the background-process scheduling on these devices is too aggressive, killing the location background service

Might be a device specific issue, we probably need some more device samples.
Affected so far is:
- LGE Nexus 5X running Android 8.1
- OnePlus 3T running Android 9 (stock)

**Comment by noerw** [comment]
Here's an anonymized sample trajectory from android: [traj.csv](https://github.com/sitcomlab/simport-learning-app/files/6378552/traj.csv)

|time|distance|xy|
|-|-|-|
|![grafik](https://user-images.githubusercontent.com/7880552/116117065-5e800a00-a6ab-11eb-99fa-05755738aefc.png)|![grafik](https://user-images.githubusercontent.com/7880552/116117166-7788bb00-a6ab-11eb-8a95-21da6bf3bc73.png)|![grafik](https://user-images.githubusercontent.com/7880552/116117286-94bd8980-a6ab-11eb-9cb2-7fcd70be3f48.png)|
|note the clustering at multiples of 600 seconds|||

```
> summary(df)
      time                       d_seconds        d_meters      
 Min.   :2021-02-25 11:00:38   Min.   :    0   Min.   :   0.00  
 1st Qu.:2021-03-01 15:44:20   1st Qu.:  617   1st Qu.:  47.26  
 Median :2021-03-02 05:32:23   Median :  924   Median :  68.97  
 Mean   :2021-03-01 18:15:43   Mean   : 1611   Mean   : 293.85  
 3rd Qu.:2021-03-02 17:15:13   3rd Qu.: 1802   3rd Qu.: 108.32  
 Max.   :2021-03-04 10:16:50   Max.   :11161   Max.   :3674.09  
     speed            accuracy     
 Min.   :-1.0000   Min.   :  5.00  
 1st Qu.:-1.0000   1st Qu.: 39.25  
 Median :-1.0000   Median : 53.00  
 Mean   :-0.1446   Mean   : 71.25  
 3rd Qu.: 0.3507   3rd Qu.: 89.75  
 Max.   : 7.8400   Max.   :249.00 
```

|walking|car & bike|
|-|-|
|![grafik](https://user-images.githubusercontent.com/7880552/116117465-ce8e9000-a6ab-11eb-90f7-355eae4a04e6.png)|![grafik](https://user-images.githubusercontent.com/7880552/116117539-dfd79c80-a6ab-11eb-9886-93a5a0175398.png)|

**Comment by zven** [comment]
Hm. That's bad. I'll pick up some additional android devices and do some further testing this week.

It might make sense to do a bit of background research on the location tracking / provider issue on Android. Apart from the fact that the operating system kills our process, the bad quality of tracking, even if the process is not killed, seems to be a separate problem.

**Comment by schrooom** [comment]
Potentially helpful:

References from [Plugin 'Background Mode'](https://ionicframework.com/docs/native/background-mode/) ([Repository](https://github.com/katzer/cordova-plugin-background-mode)):
  - [disableBatteryOptimizations](https://github.com/katzer/cordova-plugin-background-mode/blob/0a6bf35cb9f2bfcb8a0a79767b57158e17a32f13/src/android/BackgroundModeExt.java#L193) (Disables battery optimizations for the app programmatically when permission is granted)
  - [disableWebViewOptimizations](https://github.com/katzer/cordova-plugin-background-mode/blob/0a6bf35cb9f2bfcb8a0a79767b57158e17a32f13/src/android/BackgroundModeExt.java#L163) (Seems a bit hacky, I don't fully understand, what is done here)

**Comment by noerw** [comment]
#73 provides scripts that helped me do the above analysis in https://github.com/sitcomlab/simport-learning-app/issues/71#issuecomment-826974696

**Comment by noerw** [comment]
FYI:
I was looking how to enhance logging, to see if there are more location updates gathered by the foreground-service than are processed by our webview application.
I noticed that the background plugin already has extensive database logging (inspect them either via `Android Studio → View → Tool Windows → Database Explorer`, or via `... → Device File Explorer`:

- `/data/data/de.ifgi.simport.learning/databases/logback.db` contains plenty debug logs of the background location service

    Looking at the these logs, it seems the background location plugin is working as it should. I can't make sense of the different location update messages though, need to further look into this. However I noted the following log message:
    ```
    Service configured with: Config[distanceFilter=30 stationaryRadius=20.0 desiredAccuracy=10 interval=600000 fastestInterval=120000 activitiesInterval=10000 isDebugging=false stopOnTerminate=false stopOnStillActivity=true startOnBoot=false startForeground=true notificationsEnabled=true locationProvider=0 nTitle=Background tracking nT
    ```
    - Need to check what the `interval` setting means, but the value of 600000 is quite high and suspiciously matches the clustering of updates at an interval of ca ~600 seconds.
    - `stopOnStillActivity=true` is also somewhat suspicious

- `/data/data/de.ifgi.simport.learning/databases/cordova_bg_geolocation.db` contains locations as recorded by the location plugin

    Comparing the plugin's locations database with our location DB, I noticed that there are plenty more locations in the internal DB of the plugin.
    This either means, that the webview does not receive a set of the location updates, or that this internal DB contains all locations before the DISTANCE_FILTER_PROVIDER applies its filters. 🤔 Need to look into the implementation of the distance filter provider to be sure..

**Comment by schrooom** [comment]
> @noerw Need to check what the interval setting means, but the value of 600000 is quite high and suspiciously matches the clustering of updates at an interval of ca ~600 seconds.

Good find! This might already be the main cause for our problem, since this is an Android-only setting, which (obviously) defaults to 600.000. [See here:](https://github.com/mauron85/cordova-plugin-background-geolocation)
> The minimum time interval between location updates in milliseconds. @see Android docs for more information.

**Comment by schrooom** [comment]
I did some further testing with this config:
```
    desiredAccuracy: 10,
    stationaryRadius: 20,
    distanceFilter: 30,
    interval: 20000,
    debug: false,
    stopOnTerminate: false, 
    startForeground: true,
```
This is basically our current config, but the interval is set to 20s. This - again, just like config #3 - worked fine for me.

For example a short walk this morning looks like this, which resulted in ~20 locations (a few hundred meters). While a way longer trip by bike (~5km) with the old config looked resulted in ~4 locations - I'd expect many locations more here.

> Screens on this on Discord 

To me this looks quite promising to at least fix the update frequency. However: this only tackles these problems about update frequency. In my tests I wasn't able to reproduce that updates irregularly stop at some point after the background task was started (after 2h - 2days) - my test trajectories were a day long max up until now.

**Comment by zven** [comment]
TODO:
- Check in on feature branch and merge to develop
