### ISSUE TITLE
UI: Inference visualization

### ISSUE THREAD

**Issue by zven** [sitcomlab/simport-learning-app#75]
At the moment, red circular buffer around potential inference location. Diameter is longest distance between two points belonging to the cluster. At the same time, we display a confidence value in a popup.

Potential visualization:
- Size of buffer (maybe not red?) visualizes uncertainty in meters and not size of cluster?

**Comment by felixerdy** [comment]
### Current state

|Description|View|
|---|---|
|Currently, the mapview shows circle markers that identify the inference results. The radius of each circle represents the accuracy of the cluster which is the distance to the outermost point. The color is static and does not change.|![default](https://user-images.githubusercontent.com/12086004/120300867-9f7fc580-c2cc-11eb-9fbe-dacf4b79584c.png)|


### Cluster Extend
Even tough we are interested in specific locations (like home or work location), clusters may not be circular but extend to an irregular shape (which might not be supported by our current DBSCAN implementation). Furthermore, we could use the opacity of the markers to display the confidence of the inference. 
|High Confidence|Low Confidence|
|---|---|
|![confidence_high](https://user-images.githubusercontent.com/12086004/120302222-f76afc00-c2cd-11eb-9f6a-6cf6d02080f3.png)|![confidence_low](https://user-images.githubusercontent.com/12086004/120302250-ffc33700-c2cd-11eb-9a8e-bced1cf75d06.png)|

### Different colours for different locations
To identify different inferences (home and work location) we could use different colours. 
|Description|View|
|---|---|
|We should use distinguishable colours but keep color-blind individuals in mind. This view utilises safe colours based on [Wong, B. Points of view: Color blindness. Nat Methods 8, 441 (2011).](https://www.nature.com/articles/nmeth.1618)|![color_blind](https://user-images.githubusercontent.com/12086004/120302523-49ac1d00-c2ce-11eb-9c9d-2a855213037f.png)|

**Comment by schrooom** [comment]
I like the ideas so far, just two quick thoughts:

- Have you thought about/tried to display clusters using convex hulls? This could give users a better idea about where inferences come from. Currently we are indeed using (and therefore persisting) the centroid-location only, which is not suitable for complex visualizations. Therefore we'd need to store more locations for each inference or even persist whole clusters? Possibly only their convex hulls?
- I'd love to see icons on the map. Currently we use the `home` and `business`icons from ionic to display home and work-inferences in other parts of the app. I think those would look great within the map and give users an idea at first glimpse about what inferences he/she can currently see.

To combine those: We're currently using the centroids of each cluster (mean location) as the center point for the current visualization. We could for example put the respective icon on that centroid and display the corresponding cluster (as a convex hull) around that. Your ideas such as different colours and opacities could be nicely incorporated into both elements.

**Comment by zven** [comment]
I agree with @schrooom: Displaying the same markers throughout the app would definitely be beneficial. In addition, experimenting with a convex hull would be really interesting.

**Comment by schrooom** [comment]
As discussed last week: I updated the persistence of inference to store a list of coordinates (see 1444aa1). This enables storing the cluster or e.g. a convex hull of the cluster alongside each inference.
